## Pinout generated for U4 (XC7A100T-FTG256)
# set_property -dict { PACKAGE_PIN A1    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN A3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L4N_T0_35NPadA3 }];
# set_property -dict { PACKAGE_PIN A4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L3N_T0_DQS_AD5N_35NPadA4 }];
# set_property -dict { PACKAGE_PIN A5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L3P_T0_DQS_AD5P_35NPadA5 }];
# set_property -dict { PACKAGE_PIN A6    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN A7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L1N_T0_AD4N_35NPadA7 }];
set_property -dict { PACKAGE_PIN A8    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_MOSI }];
set_property -dict { PACKAGE_PIN A9    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_GPIO0 }];
set_property -dict { PACKAGE_PIN A10    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_GPIO2 }];
# set_property -dict { PACKAGE_PIN A11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN A12    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_GPIO6 }];
# set_property -dict { PACKAGE_PIN A13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L7P_T1_AD2P_15NPadA13 }];
# set_property -dict { PACKAGE_PIN A14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L7N_T1_AD2N_15NPadA14 }];
# set_property -dict { PACKAGE_PIN A15    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L9N_T1_DQS_AD3N_15NPadA15 }];
# set_property -dict { PACKAGE_PIN A16    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN B3    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN B4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L4P_T0_35NPadB4 }];
# set_property -dict { PACKAGE_PIN B5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L2N_T0_AD12N_35NPadB5 }];
# set_property -dict { PACKAGE_PIN B6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L2P_T0_AD12P_35NPadB6 }];
# set_property -dict { PACKAGE_PIN B7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L1P_T0_AD4P_35NPadB7 }];
# set_property -dict { PACKAGE_PIN B8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN B9    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_GPIO1 }];
set_property -dict { PACKAGE_PIN B10    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_GPIO3 }];
set_property -dict { PACKAGE_PIN B11    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_GPIO4 }];
set_property -dict { PACKAGE_PIN B12    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_GPIO5 }];
# set_property -dict { PACKAGE_PIN B13    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN B14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L8N_T1_AD10N_15NPadB14 }];
# set_property -dict { PACKAGE_PIN B15    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L9P_T1_DQS_AD3P_15NPadB15 }];
# set_property -dict { PACKAGE_PIN B16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L10N_T1_AD11N_15NPadB16 }];
# set_property -dict { PACKAGE_PIN C3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L7P_T1_AD6P_35NPadC3 }];
# set_property -dict { PACKAGE_PIN C5    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L5N_T0_AD13N_35NPadC6 }];
# set_property -dict { PACKAGE_PIN C7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L5P_T0_AD13P_35NPadC7 }];
set_property -dict { PACKAGE_PIN C8    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_CS }];
set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_MISO }];
# set_property -dict { PACKAGE_PIN C10    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN C11    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L11P_T1_SRCC_15 }];
set_property -dict { PACKAGE_PIN C12    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L11N_T1_SRCC_15 }];
set_property -dict { PACKAGE_PIN C13    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L12N_T1_MRCC_15 }];
# set_property -dict { PACKAGE_PIN C14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L8P_T1_AD10P_15NPadC14 }];
# set_property -dict { PACKAGE_PIN C15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L10P_T1_AD11P_15NPadC16 }];
# set_property -dict { PACKAGE_PIN D2    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN D5    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4BNIO_L6N_T0_VREF_35 }];
# set_property -dict { PACKAGE_PIN D6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L6P_T0_35NPadD6 }];
# set_property -dict { PACKAGE_PIN D7    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN D8    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_GPIO7 }];
# set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L6N_T0_VREF_15NPadD9 }];
set_property -dict { PACKAGE_PIN D10    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_CLK }];
set_property -dict { PACKAGE_PIN D11    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L14N_T2_SRCC_15 }];
# set_property -dict { PACKAGE_PIN D12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN D13    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L12P_T1_MRCC_15 }];
set_property -dict { PACKAGE_PIN D14    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L15P_T2_DQS_15 }];
set_property -dict { PACKAGE_PIN D15    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L15N_T2_DQS_ADV_B_15 }];
set_property -dict { PACKAGE_PIN D16    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L17N_T2_A25_15 }];
# set_property -dict { PACKAGE_PIN E4    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN E6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_0_35NPadE6 }];
set_property -dict { PACKAGE_PIN E7    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN E8    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNIC1NSCK }];
# set_property -dict { PACKAGE_PIN E9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E10    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
set_property -dict { PACKAGE_PIN E11    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L14P_T2_SRCC_15 }];
set_property -dict { PACKAGE_PIN E12    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L13P_T2_MRCC_15 }];
set_property -dict { PACKAGE_PIN E13    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L13N_T2_MRCC_15 }];
# set_property -dict { PACKAGE_PIN E14    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN E15    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L18N_T2_A23_15 }];
set_property -dict { PACKAGE_PIN E16    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L17P_T2_A26_15 }];
# set_property -dict { PACKAGE_PIN F1    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN F6    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F7    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN F8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F9    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN F10    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F11    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
set_property -dict { PACKAGE_PIN F12    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L16P_T2_A28_15 }];
set_property -dict { PACKAGE_PIN F13    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L16N_T2_A27_15 }];
set_property -dict { PACKAGE_PIN F14    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L21N_T3_DQS_A18_15 }];
set_property -dict { PACKAGE_PIN F15    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L18P_T2_A24_15 }];
# set_property -dict { PACKAGE_PIN F16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G3    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G6    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN G7    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G8    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN G9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G10    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
set_property -dict { PACKAGE_PIN G11    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_25_15 }];
set_property -dict { PACKAGE_PIN G12    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L19N_T3_A21_VREF_15 }];
# set_property -dict { PACKAGE_PIN G13    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN G14    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L21P_T3_DQS_15 }];
set_property -dict { PACKAGE_PIN G15    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L24N_T3_RS0_15 }];
set_property -dict { PACKAGE_PIN G16    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L22N_T3_A16_15 }];
# set_property -dict { PACKAGE_PIN H6    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN H7    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H9    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
set_property -dict { PACKAGE_PIN H10    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_done }];
set_property -dict { PACKAGE_PIN H11    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L19P_T3_A22_15 }];
set_property -dict { PACKAGE_PIN H12    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L20P_T3_A20_15 }];
set_property -dict { PACKAGE_PIN H13    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L20N_T3_A19_15 }];
set_property -dict { PACKAGE_PIN H14    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L24P_T3_RS1_15 }];
# set_property -dict { PACKAGE_PIN H15    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN H16    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L22P_T3_A17_15 }];
# set_property -dict { PACKAGE_PIN J1    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L22N_T3_35NPadJ1 }];
# set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN J4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L19N_T3_VREF_35NPadJ4 }];
# set_property -dict { PACKAGE_PIN J6    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN J7    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J10    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN J11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J12    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN J13    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNIC1NSI_slash_IO0 }];
set_property -dict { PACKAGE_PIN J14    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNIC1NSO_slash_IO1 }];
set_property -dict { PACKAGE_PIN J15    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L23P_T3_FOE_B_15 }];
set_property -dict { PACKAGE_PIN J16    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L23N_T3_FWE_B_15 }];
# set_property -dict { PACKAGE_PIN K2    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L24N_T3_35NPadK2 }];
# set_property -dict { PACKAGE_PIN K3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L24P_T3_35NPadK3 }];
# set_property -dict { PACKAGE_PIN K4    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_25_35NPadK5 }];
# set_property -dict { PACKAGE_PIN K6    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4CNDXN_0NPadK7 }];
# set_property -dict { PACKAGE_PIN K8    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4CNDXP_0NPadK8 }];
# set_property -dict { PACKAGE_PIN K9    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
set_property -dict { PACKAGE_PIN K10    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4CNINIT_B_0 }];
# set_property -dict { PACKAGE_PIN K11    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN K12    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_0_14NPadK12 }];
# set_property -dict { PACKAGE_PIN K13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L5P_T0_D06_14NPadK13 }];
# set_property -dict { PACKAGE_PIN K14    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN K15    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNIC1NWP_slash_IO2 }];
set_property -dict { PACKAGE_PIN K16    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNIC1NIO3_slash_RESET }];
# set_property -dict { PACKAGE_PIN L1    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L2    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L23N_T3_35NPadL2 }];
# set_property -dict { PACKAGE_PIN L3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L23P_T3_35NPadL3 }];
# set_property -dict { PACKAGE_PIN L6    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN L7    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4CNTCK_0 }];
# set_property -dict { PACKAGE_PIN L8    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
set_property -dict { PACKAGE_PIN L9    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_program_b }];
# set_property -dict { PACKAGE_PIN L10    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN L11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN L12    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNIC1NCS }];
# set_property -dict { PACKAGE_PIN L13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L5N_T0_D07_14NPadL13 }];
# set_property -dict { PACKAGE_PIN L14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L4P_T0_D04_14NPadL14 }];
# set_property -dict { PACKAGE_PIN L15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L16    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN M2    IOSTANDARD LVCMOS33 } [get_ports { pin_FPGA_RED3 }];
# set_property -dict { PACKAGE_PIN M3    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN M6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L19P_T3_A10_D26_14NPadM6 }];
set_property -dict { PACKAGE_PIN M7    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4CNTMS_0 }];
# set_property -dict { PACKAGE_PIN M8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M9    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN M10    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M12    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L6N_T0_D08_VREF_14NPadM12 }];
# set_property -dict { PACKAGE_PIN M13    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN M14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L4N_T0_D05_14NPadM14 }];
# set_property -dict { PACKAGE_PIN M15    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L3N_T0_DQS_EMCCLK_14NPadM15 }];
# set_property -dict { PACKAGE_PIN M16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L7P_T1_D09_14NPadM16 }];
# set_property -dict { PACKAGE_PIN N5    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L19N_T3_A09_D25_VREF_14NPadN6 }];
set_property -dict { PACKAGE_PIN N7    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4CNTDI_0 }];
set_property -dict { PACKAGE_PIN N8    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4CNTDO_0 }];
# set_property -dict { PACKAGE_PIN N9    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L18P_T2_A12_D28_14NPadN9 }];
# set_property -dict { PACKAGE_PIN N10    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN N11    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L13P_T2_MRCC_14 }];
# set_property -dict { PACKAGE_PIN N12    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L13N_T2_MRCC_14NPadN12 }];
# set_property -dict { PACKAGE_PIN N13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L11P_T1_SRCC_14NPadN13 }];
# set_property -dict { PACKAGE_PIN N14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L12P_T1_MRCC_14NPadN14 }];
# set_property -dict { PACKAGE_PIN N15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L7N_T1_D10_14NPadN16 }];
# set_property -dict { PACKAGE_PIN P2    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L10P_T1_34NPadP5 }];
# set_property -dict { PACKAGE_PIN P6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_25_14NPadP6 }];
# set_property -dict { PACKAGE_PIN P7    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN P8    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L20P_T3_A08_D24_14NPadP8 }];
# set_property -dict { PACKAGE_PIN P9    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L18N_T2_A11_D27_14NPadP9 }];
# set_property -dict { PACKAGE_PIN P10    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L14P_T2_SRCC_14NPadP10 }];
# set_property -dict { PACKAGE_PIN P11    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L14N_T2_SRCC_14NPadP11 }];
# set_property -dict { PACKAGE_PIN P12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L11N_T1_SRCC_14NPadP13 }];
# set_property -dict { PACKAGE_PIN P14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L12N_T1_MRCC_14NPadP14 }];
# set_property -dict { PACKAGE_PIN P15    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L8P_T1_D11_14NPadP15 }];
# set_property -dict { PACKAGE_PIN P16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L8N_T1_D12_14NPadP16 }];
# set_property -dict { PACKAGE_PIN R4    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN R5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L23P_T3_A03_D19_14NPadR5 }];
# set_property -dict { PACKAGE_PIN R6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L24P_T3_A01_D17_14NPadR6 }];
# set_property -dict { PACKAGE_PIN R7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L24N_T3_A00_D16_14NPadR7 }];
# set_property -dict { PACKAGE_PIN R8    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L20N_T3_A07_D23_14NPadR8 }];
# set_property -dict { PACKAGE_PIN R9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R10    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L17P_T2_A14_D30_14NPadR10 }];
set_property -dict { PACKAGE_PIN R11    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L17N_T2_A13_D29_14 }];
set_property -dict { PACKAGE_PIN R12    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L15P_T2_DQS_RDWR_B_14 }];
set_property -dict { PACKAGE_PIN R13    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L16P_T2_CSI_B_14 }];
# set_property -dict { PACKAGE_PIN R14    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN R15    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L9P_T1_DQS_14 }];
# set_property -dict { PACKAGE_PIN R16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L9N_T1_DQS_D13_14NPadR16 }];
# set_property -dict { PACKAGE_PIN T1    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
# set_property -dict { PACKAGE_PIN T3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L9N_T1_DQS_34NPadT3 }];
# set_property -dict { PACKAGE_PIN T4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4BNIO_L9P_T1_DQS_34NPadT4 }];
# set_property -dict { PACKAGE_PIN T5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L23N_T3_A02_D18_14NPadT5 }];
# set_property -dict { PACKAGE_PIN T6    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN T7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L21P_T3_DQS_14NPadT7 }];
# set_property -dict { PACKAGE_PIN T8    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L21N_T3_DQS_A06_D22_14NPadT8 }];
# set_property -dict { PACKAGE_PIN T9    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L22P_T3_A05_D21_14NPadT9 }];
# set_property -dict { PACKAGE_PIN T10    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU4ANIO_L22N_T3_A04_D20_14NPadT10 }];
# set_property -dict { PACKAGE_PIN T11    IOSTANDARD LVCMOS33 } [get_ports { pin_P33V }];
set_property -dict { PACKAGE_PIN T12    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L15N_T2_DQS_DOUT_CSO_B_14 }];
set_property -dict { PACKAGE_PIN T13    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L16N_T2_A15_D31_14 }];
set_property -dict { PACKAGE_PIN T14    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L10P_T1_D14_14 }];
set_property -dict { PACKAGE_PIN T15    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU4ANIO_L10N_T1_D15_14 }];
# set_property -dict { PACKAGE_PIN T16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];

### VGA ###

# VGA red
set_property -dict { PACKAGE_PIN L5    IOSTANDARD LVCMOS33 } [get_ports { vga_red[0] }];
set_property -dict { PACKAGE_PIN L4    IOSTANDARD LVCMOS33 } [get_ports { vga_red[1] }];
set_property -dict { PACKAGE_PIN M4    IOSTANDARD LVCMOS33 } [get_ports { vga_red[2] }];
set_property -dict { PACKAGE_PIN M2    IOSTANDARD LVCMOS33 } [get_ports { vga_red[3] }];
set_property -dict { PACKAGE_PIN M1    IOSTANDARD LVCMOS33 } [get_ports { vga_red[4] }];

# VGA green
set_property -dict { PACKAGE_PIN N3    IOSTANDARD LVCMOS33 } [get_ports { vga_green[0] }];
set_property -dict { PACKAGE_PIN N2    IOSTANDARD LVCMOS33 } [get_ports { vga_green[1] }];
set_property -dict { PACKAGE_PIN N1    IOSTANDARD LVCMOS33 } [get_ports { vga_green[2] }];
set_property -dict { PACKAGE_PIN P1    IOSTANDARD LVCMOS33 } [get_ports { vga_green[3] }];
set_property -dict { PACKAGE_PIN P4    IOSTANDARD LVCMOS33 } [get_ports { vga_green[4] }];

# VGA blue
set_property -dict { PACKAGE_PIN P3    IOSTANDARD LVCMOS33 } [get_ports { vga_blue[0] }];
set_property -dict { PACKAGE_PIN M5    IOSTANDARD LVCMOS33 } [get_ports { vga_blue[1] }];
set_property -dict { PACKAGE_PIN N4    IOSTANDARD LVCMOS33 } [get_ports { vga_blue[2] }];
set_property -dict { PACKAGE_PIN R2    IOSTANDARD LVCMOS33 } [get_ports { vga_blue[3] }];
set_property -dict { PACKAGE_PIN R1    IOSTANDARD LVCMOS33 } [get_ports { vga_blue[4] }];

# VGA syncs
set_property -dict { PACKAGE_PIN R3    IOSTANDARD LVCMOS33 } [get_ports { vga_vsync }];
set_property -dict { PACKAGE_PIN T2    IOSTANDARD LVCMOS33 } [get_ports { vga_hsync }];


### LCD ###

# LCD red
set_property -dict { PACKAGE_PIN C2    IOSTANDARD LVCMOS33 } [get_ports { lcd_red[0] }];
set_property -dict { PACKAGE_PIN B2    IOSTANDARD LVCMOS33 } [get_ports { lcd_red[1] }];
set_property -dict { PACKAGE_PIN A2    IOSTANDARD LVCMOS33 } [get_ports { lcd_red[2] }];
set_property -dict { PACKAGE_PIN C1    IOSTANDARD LVCMOS33 } [get_ports { lcd_red[3] }];
set_property -dict { PACKAGE_PIN B1    IOSTANDARD LVCMOS33 } [get_ports { lcd_red[4] }];
set_property -dict { PACKAGE_PIN E2    IOSTANDARD LVCMOS33 } [get_ports { lcd_red[5] }];
set_property -dict { PACKAGE_PIN D1    IOSTANDARD LVCMOS33 } [get_ports { lcd_red[6] }];
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { lcd_red[7] }];

# LCD green
set_property -dict { PACKAGE_PIN D3    IOSTANDARD LVCMOS33 } [get_ports { lcd_green[0] }];
set_property -dict { PACKAGE_PIN D4    IOSTANDARD LVCMOS33 } [get_ports { lcd_green[1] }];
set_property -dict { PACKAGE_PIN C4    IOSTANDARD LVCMOS33 } [get_ports { lcd_green[2] }];
set_property -dict { PACKAGE_PIN F5    IOSTANDARD LVCMOS33 } [get_ports { lcd_green[3] }];
set_property -dict { PACKAGE_PIN E5    IOSTANDARD LVCMOS33 } [get_ports { lcd_green[4] }];
set_property -dict { PACKAGE_PIN F4    IOSTANDARD LVCMOS33 } [get_ports { lcd_green[5] }];
set_property -dict { PACKAGE_PIN F3    IOSTANDARD LVCMOS33 } [get_ports { lcd_green[6] }];
set_property -dict { PACKAGE_PIN F2    IOSTANDARD LVCMOS33 } [get_ports { lcd_green[7] }];

# LCD blue
set_property -dict { PACKAGE_PIN E1    IOSTANDARD LVCMOS33 } [get_ports { lcd_blue[0] }];
set_property -dict { PACKAGE_PIN G5    IOSTANDARD LVCMOS33 } [get_ports { lcd_blue[1] }];
set_property -dict { PACKAGE_PIN G4    IOSTANDARD LVCMOS33 } [get_ports { lcd_blue[2] }];
set_property -dict { PACKAGE_PIN G2    IOSTANDARD LVCMOS33 } [get_ports { lcd_blue[3] }];
set_property -dict { PACKAGE_PIN G1    IOSTANDARD LVCMOS33 } [get_ports { lcd_blue[4] }];
set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { lcd_blue[5] }];
set_property -dict { PACKAGE_PIN H4    IOSTANDARD LVCMOS33 } [get_ports { lcd_blue[6] }];
set_property -dict { PACKAGE_PIN J5    IOSTANDARD LVCMOS33 } [get_ports { lcd_blue[7] }];

# LCD control
set_property -dict { PACKAGE_PIN H2    IOSTANDARD LVCMOS33 } [get_ports { lcd_dot_clk }];
set_property -dict { PACKAGE_PIN H1    IOSTANDARD LVCMOS33 } [get_ports { lcd_display }];

# LCD syncs
set_property -dict { PACKAGE_PIN J3    IOSTANDARD LVCMOS33 } [get_ports { lcd_hsync }];
set_property -dict { PACKAGE_PIN H3    IOSTANDARD LVCMOS33 } [get_ports { lcd_vsync }];

# LCD data enable
set_property -dict { PACKAGE_PIN K1    IOSTANDARD LVCMOS33 } [get_ports { lcd_de }];